apiVersion: v1
kind: Template
labels:
  template: citrus-testing
metadata:
  annotations:
    description: citrus integration testing
    iconClass: icon-beaker
    tags: consol, citrus, integration-testing
    version: 1.1.0
  creationTimestamp: null
  name: citrus-testing
### template parameter defined via `oc process -f this.yaml -v PARAMETER=value`
parameters:
## REQUIRED
- name: CITRUS_TEST_NAME
  description: The name for the citrus test
  required: true
  value: citrus-test
## OPTIONAL
- description: 'Custom hostname for http service route.  Leave blank for default hostname, e.g.: <CITRUS_TEST_NAME-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME_HTTP
### Configuration of OpenShift objects
objects:
### POD config (run one time)
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      application: ${CITRUS_TEST_NAME}
    name: ${CITRUS_TEST_NAME}
  spec:
    ### ensure that the pod won't start again
    restartPolicy: Never
    dnsPolicy: ClusterFirst
    terminationGracePeriodSeconds: 5
    containers:
    - name: ${CITRUS_TEST_NAME}
      image: consol/citrus-admin:latest
      imagePullPolicy: IfNotPresent
      env:
      - name: CITRUS_ADMIN_ROOT_DIRECTORY
        value: '/maven'
      - name: CITRUS_ADMIN_PROJECT_REPOSITORY
        value: 'https://github.com/oweise/sakuli-example-bakery-testing'
      - name: CITRUS_ADMIN_PROJECT_REPOSITORY_MODULE
        value: 'citrus-tests'
      ### checks if http-vnc connection is working
      readinessProbe:
        httpGet:
          path: /
          port: 6901
          scheme: HTTP
        initialDelaySeconds: 1
        timeoutSeconds: 1
      volumeMounts:
      - name: projects
        mountPath: /maven
    volumes:
    - name: projects
      emptyDir: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: ${CITRUS_TEST_NAME}
    labels:
      application: ${CITRUS_TEST_NAME}
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      application: ${CITRUS_TEST_NAME}
    type: ClusterIP
    sessionAffinity: None
- apiVersion: v1
  id: ${CITRUS_TEST_NAME}
  kind: Route
  metadata:
    name: ${CITRUS_TEST_NAME}
    labels:
      application: ${CITRUS_TEST_NAME}
  spec:
    host: ${HOSTNAME_HTTP}
    to:
      kind: Service
      name: ${CITRUS_TEST_NAME}
    port:
      targetPort: 8080-tcp
    wildcardPolicy: None
