apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: build-ci-delete
parameters:
#REQUIERD
  - name: STAGE
    required: true
#OPTIONAL
  - name: APP_NAME
    required: true
    value: 'bakery-delete-ci'
  - name: GIT_URL
    required: true
    value: 'https://github.com/toschneck/openshift-example-bakery-ci-pipeline'
  - name: GIT_BRANCH
    required: true
    value: 'master'
  - name: GIT_PATH
    required: false
    value: ''
  - name: GITHUB_WEBHOOK_SECRET
    description: GitHub trigger secret
    from: '[a-zA-Z0-9]{8}'
    generate: expression
    required: true
  - name: GENERIC_WEBHOOK_SECRET
    description: Generic build trigger secret
    from: '[a-zA-Z0-9]{8}'
    generate: expression
    required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: ${APP_NAME}
    labels:
      application: ${APP_NAME}
      stage: dev
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: ${GIT_BRANCH}
        uri: ${GIT_URL}
      contextDir: ${GIT_PATH}
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfile: |-
          node('') {
            stage ('checkout') {
              git branch: '${GIT_BRANCH}', url: '${GIT_URL}'
              sh "ls -la ."
              sh "oc project oshift-day-${STAGE}"
            }
            stage ('delete bakery-app') {
              sh "openshift/bakery-app/create_activemq.sh delete"
              sh "openshift/bakery-app/create_bakery-report-server.sh delete"
              sh "openshift/bakery-app/create_bakery-web-server.sh delete"
              sh "openshift/bakery-app/create_bakery-workers.sh delete"
            }
            stage ('delete ui-tests') {
              sh "openshift/sakuli-tests/create_wait-server.sh delete"
              sh "openshift/sakuli-tests/create_sakuli-test.sh delete blueberry"
              sh "openshift/sakuli-tests/create_sakuli-test.sh delete caramel"
              sh "openshift/sakuli-tests/create_sakuli-test.sh delete chocolate"
              sh "openshift/sakuli-tests/create_sakuli-test.sh delete order-pdf"
            }
          }
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      application: ${APP_NAME}
      stage: dev
    name: ${APP_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      application: ${APP_NAME}
      role: jenkins-slave
    name: maven
  spec:
#    dockerImageRepository: docker.io/openshift/jenkins-slave-maven-centos7
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker.io/openshift/jenkins-slave-maven-centos7
      generation: 1
      importPolicy:
        scheduled: true
      name: latest
